version: "2017-09-20"

pipeline:
- id: build
  type: script
  overlay: ci/clojure
  env:
    LEIN_ROOT: true
  commands:
  - desc: Build and test
    cmd: |
      lein do clean, test, uberjar
  - desc: Build docker image
    cmd: |
      IMAGE="pierone.stups.zalan.do/teapot/even:cdp${CDP_TARGET_REPOSITORY_COUNTER}"
      docker build -t "$IMAGE" .
      if [[ "${CDP_TARGET_BRANCH}" = "master" && -z "${CDP_PULL_REQUEST_NUMBER}" ]]; then
        docker push "$IMAGE"
      fi
